import re

extra_bases = """
    # MORE MEATS
    ("duck_breast", (337, 19.0, 28.0, 0.0), "meat", ["raw", "baked", "fried", "grilled"],
     ("Duck Breast", "Утиная грудка", "Entenbrust", "Pechuga de pato", "Magret de canard", "Petto d'anatra")),
    ("lamb_chop", (294, 25.0, 21.0, 0.0), "meat", ["raw", "baked", "fried", "grilled"],
     ("Lamb Chop", "Баранья отбивная", "Lammkotelett", "Chuleta de cordero", "Côtelette d'agneau", "Costoletta di agnello")),
    ("veal_cutlet", (112, 21.0, 2.5, 0.0), "meat", ["raw", "fried", "grilled", "baked"],
     ("Veal Cutlet", "Телячья отбивная", "Kalbskotelett", "Chuleta de ternera", "Escalope de veau", "Cotoletta di vitello")),
    ("venison", (158, 30.0, 3.2, 0.0), "meat", ["raw", "fried", "grilled"],
     ("Venison", "Оленина", "Hirschfleisch", "Carne de venado", "Viande de cerf", "Carne di cervo")),
    ("sausage_pork", (301, 14.0, 27.0, 0.0), "meat", ["raw", "fried", "grilled", "boiled"],
     ("Pork Sausage", "Свиная сосиска", "Schweinswurst", "Salchicha de cerdo", "Saucisse de porc", "Salsiccia di maiale")),

    # MORE FISH & SEAFOOD
    ("mackerel", (305, 19.0, 25.0, 0.0), "fish", ["raw", "fried", "grilled", "baked", "canned"],
     ("Mackerel", "Скумбрия", "Makrele", "Caballa", "Maquereau", "Sgombro")),
    ("herring", (203, 23.0, 11.0, 0.0), "fish", ["raw", "fried", "baked"],
     ("Herring", "Сельдь", "Hering", "Arenque", "Hareng", "Aringa")),
    ("sardines", (208, 25.0, 11.0, 0.0), "fish", ["raw", "canned", "grilled"],
     ("Sardines", "Сардины", "Sardinen", "Sardinas", "Sardines", "Sardine")),
    ("octopus", (82, 15.0, 1.0, 2.2), "fish", ["raw", "boiled", "grilled"],
     ("Octopus", "Осьминог", "Oktopus", "Pulpo", "Poulpe", "Polpo")),
    ("squid", (92, 16.0, 1.4, 3.1), "fish", ["raw", "fried", "grilled", "boiled"],
     ("Squid", "Кальмар", "Tintenfisch", "Calamar", "Calamar", "Calamaro")),
    ("mussels", (172, 24.0, 4.5, 7.4), "fish", ["raw", "boiled", "steamed"],
     ("Mussels", "Мидии", "Muscheln", "Mejillones", "Moules", "Cozze")),
    ("crab", (87, 18.0, 1.5, 0.0), "fish", ["raw", "boiled", "canned"],
     ("Crab", "Краб", "Krabbe", "Cangrejo", "Crabe", "Granchio")),
    ("lobster", (89, 19.0, 0.9, 0.0), "fish", ["raw", "boiled", "steamed", "grilled"],
     ("Lobster", "Омар / Лобстер", "Hummer", "Langosta", "Homard", "Aragosta")),
    ("trout", (148, 21.0, 6.6, 0.0), "fish", ["raw", "baked", "grilled", "fried"],
     ("Trout", "Форель", "Forelle", "Trucha", "Truite", "Trota")),

    # MORE VEGETABLES
    ("cauliflower", (25, 1.9, 0.3, 5.0), "vegetables", ["raw", "boiled", "steamed", "baked"],
     ("Cauliflower", "Цветная капуста", "Blumenkohl", "Coliflor", "Chou-fleur", "Cavolfiore")),
    ("asparagus", (20, 2.2, 0.1, 3.9), "vegetables", ["raw", "boiled", "steamed", "grilled"],
     ("Asparagus", "Спаржа", "Spargel", "Espárragos", "Asperges", "Asparagi")),
    ("green_beans", (31, 1.8, 0.2, 7.0), "vegetables", ["raw", "boiled", "steamed"],
     ("Green Beans", "Зелёная фасоль", "Grüne Bohnen", "Judías verdes", "Haricots verts", "Fagiolini")),
    ("pumpkin", (26, 1.0, 0.1, 6.5), "vegetables", ["raw", "baked", "boiled"],
     ("Pumpkin", "Тыква", "Kürbis", "Calabaza", "Citrouille", "Zucca")),
    ("celery", (16, 0.7, 0.2, 3.0), "vegetables", ["raw", "boiled"],
     ("Celery", "Сельдерей", "Sellerie", "Apio", "Céleri", "Sedano")),
    ("cucumber", (15, 0.7, 0.1, 3.6), "vegetables", ["raw"],
     ("Cucumber", "Огурец", "Gurke", "Pepino", "Concombre", "Cetriolo")),
    ("radish", (16, 0.7, 0.1, 3.4), "vegetables", ["raw"],
     ("Radish", "Редис", "Radieschen", "Rábano", "Radis", "Ravanello")),
    ("beetroot", (43, 1.6, 0.2, 9.6), "vegetables", ["raw", "boiled", "baked"],
     ("Beetroot", "Свёкла", "Rote Bete", "Remolacha", "Betterave", "Barbabietola")),
    ("brussels_sprouts", (43, 3.4, 0.3, 9.0), "vegetables", ["raw", "boiled", "steamed", "baked"],
     ("Brussels Sprouts", "Брюссельская капуста", "Rosenkohl", "Coles de Bruselas", "Choux de Bruxelles", "Cavoletti di Bruxelles")),
    ("kale", (49, 4.3, 0.9, 8.8), "vegetables", ["raw", "boiled", "steamed"],
     ("Kale", "Кейл", "Grünkohl", "Kale", "Chou frisé", "Cavolo nero")),
    ("artichoke", (47, 3.3, 0.2, 10.5), "vegetables", ["raw", "boiled", "canned"],
     ("Artichoke", "Артишок", "Artischocke", "Alcachofa", "Artichaut", "Carciofo")),
    ("leek", (61, 1.5, 0.3, 14.0), "vegetables", ["raw", "boiled", "fried"],
     ("Leek", "Лук-порей", "Lauch", "Puerro", "Poireau", "Porro")),

    # MORE FRUITS
    ("pear", (57, 0.4, 0.1, 15.0), "fruits", ["raw", "dried", "canned", "baked"],
     ("Pear", "Груша", "Birne", "Pera", "Poire", "Pera")),
    ("plum", (46, 0.7, 0.3, 11.4), "fruits", ["raw", "dried"],
     ("Plum", "Слива", "Pflaume", "Ciruela", "Prune", "Prugna")),
    ("cherry", (63, 1.1, 0.2, 16.0), "fruits", ["raw", "canned", "dried"],
     ("Cherry", "Вишня / Черешня", "Kirsche", "Cereza", "Cerise", "Ciliegia")),
    ("apricot", (48, 1.4, 0.4, 11.0), "fruits", ["raw", "dried", "canned"],
     ("Apricot", "Абрикос", "Aprikose", "Albaricoque", "Abricot", "Albicocca")),
    ("watermelon", (30, 0.6, 0.2, 7.6), "fruits", ["raw"],
     ("Watermelon", "Арбуз", "Wassermelone", "Sandía", "Pastèque", "Anguria")),
    ("melon", (34, 0.8, 0.2, 8.2), "fruits", ["raw", "dried"],
     ("Melon", "Дыня", "Melone", "Melón", "Melon", "Melone")),
    ("kiwi", (61, 1.1, 0.5, 15.0), "fruits", ["raw", "dried"],
     ("Kiwi", "Киви", "Kiwi", "Kiwi", "Kiwi", "Kiwi")),
    ("lemon", (29, 1.1, 0.3, 9.3), "fruits", ["raw"],
     ("Lemon", "Лимон", "Zitrone", "Limón", "Citron", "Limone")),
    ("blueberry", (57, 0.7, 0.3, 14.0), "fruits", ["raw", "dried", "canned"],
     ("Blueberry", "Черника", "Blaubeere", "Arándano", "Myrtille", "Mirtillo")),
    ("raspberry", (52, 1.2, 0.7, 12.0), "fruits", ["raw", "dried", "canned"],
     ("Raspberry", "Малина", "Himbeere", "Frambuesa", "Framboise", "Lampone")),
    ("blackberry", (43, 1.4, 0.5, 10.0), "fruits", ["raw"],
     ("Blackberry", "Ежевика", "Brombeere", "Zarzamora", "Mûre", "Mora")),
    ("papaya", (43, 0.5, 0.3, 11.0), "fruits", ["raw", "dried"],
     ("Papaya", "Папайя", "Papaya", "Papaya", "Papaye", "Papaya")),
    ("fig", (74, 0.8, 0.3, 19.0), "fruits", ["raw", "dried"],
     ("Fig", "Инжир", "Feige", "Higo", "Figue", "Fico")),
    ("pomegranate", (83, 1.7, 1.2, 19.0), "fruits", ["raw"],
     ("Pomegranate", "Гранат", "Granatapfel", "Granada", "Grenade", "Melograno")),

    # MORE GRAINS
    ("barley", (354, 12.0, 2.3, 73.0), "grains", ["raw", "boiled"],
     ("Barley", "Ячмень", "Gerste", "Cebada", "Orge", "Orzo")),
    ("millet", (378, 11.0, 4.2, 73.0), "grains", ["raw", "boiled"],
     ("Millet", "Пшено", "Hirse", "Mijo", "Millet", "Miglio")),
    ("couscous", (376, 13.0, 0.6, 77.0), "grains", ["raw", "boiled"],
     ("Couscous", "Кускус", "Couscous", "Cuscús", "Couscous", "Couscous")),
    ("bulgur", (342, 12.0, 1.3, 76.0), "grains", ["raw", "boiled"],
     ("Bulgur", "Булгур", "Bulgur", "Bulgur", "Boulgour", "Bulgur")),
    ("amaranth", (371, 14.0, 7.0, 65.0), "grains", ["raw", "boiled"],
     ("Amaranth", "Амарант", "Amaranth", "Amaranto", "Amaranthe", "Amaranto")),

    # MORE LEGUMES
    ("kidney_beans", (127, 8.7, 0.5, 23.0), "legumes", ["boiled", "canned"],
     ("Kidney Beans", "Красная фасоль", "Kidneybohnen", "Frijoles rojos", "Haricots rouges", "Fagioli rossi")),
    ("white_beans", (139, 9.7, 0.4, 25.0), "legumes", ["boiled", "canned"],
     ("White Beans", "Белая фасоль", "Weiße Bohnen", "Alubias blancas", "Haricots blancs", "Fagioli bianchi")),
    ("soybeans", (147, 13.0, 6.8, 11.0), "legumes", ["boiled"],
     ("Soybeans", "Соевые бобы", "Sojabohnen", "Soja", "Graines de soja", "Soia")),
    ("tofu", (76, 8.0, 4.8, 1.9), "legumes", ["raw", "fried", "baked"],
     ("Tofu", "Тофу", "Tofu", "Tofu", "Tofu", "Tofu")),

    # MORE DAIRY & EGGS
    ("cheese_parmesan", (431, 38.0, 29.0, 4.1), "dairy", ["raw"],
     ("Parmesan", "Пармезан", "Parmesan", "Parmesano", "Parmesan", "Parmigiano")),
    ("cheese_brie", (334, 21.0, 28.0, 0.5), "dairy", ["raw", "baked"],
     ("Brie", "Бри", "Brie", "Brie", "Brie", "Brie")),
    ("cheese_feta", (264, 14.0, 21.0, 4.1), "dairy", ["raw", "baked"],
     ("Feta", "Фета", "Feta", "Feta", "Feta", "Feta")),
    ("cottage_cheese", (98, 11.0, 4.3, 3.4), "dairy", ["raw"],
     ("Cottage Cheese", "Творог", "Hüttenkäse", "Queso cottage", "Fromage cottage", "Fiocchi di latte")),
    ("sour_cream", (214, 2.4, 22.0, 2.9), "dairy", ["raw"],
     ("Sour Cream", "Сметана", "Sauerrahm", "Crema agria", "Crème aigre", "Panna acida")),
    ("kefir", (60, 3.3, 3.0, 4.0), "dairy", ["raw"],
     ("Kefir", "Кефир", "Kefir", "Kéfir", "Kéfir", "Kefir")),
    ("quail_egg", (158, 13.0, 11.0, 0.4), "eggs", ["raw", "boiled", "fried"],
     ("Quail Egg", "Перепелиное яйцо", "Wachtelei", "Huevo de codorniz", "Œuf de caille", "Uovo di quaglia")),

    # MORE NUTS & SEEDS
    ("cashews", (553, 18.0, 44.0, 30.0), "nuts", ["raw", "baked"],
     ("Cashews", "Кешью", "Cashewnüsse", "Anacardos", "Noix de cajou", "Anacardi")),
    ("pistachios", (562, 20.0, 45.0, 28.0), "nuts", ["raw", "baked"],
     ("Pistachios", "Фисташки", "Pistazien", "Pistachos", "Pistaches", "Pistacchi")),
    ("hazelnuts", (628, 15.0, 61.0, 17.0), "nuts", ["raw"],
     ("Hazelnuts", "Фундук", "Haselnüsse", "Avellanas", "Noisettes", "Nocciole")),
    ("macadamia", (718, 7.9, 76.0, 14.0), "nuts", ["raw"],
     ("Macadamia", "Макадамия", "Macadamia", "Macadamia", "Macadamia", "Macadamia")),
    ("pecans", (691, 9.0, 72.0, 14.0), "nuts", ["raw"],
     ("Pecans", "Пекан", "Pekannüsse", "Nueces pecanas", "Noix de pécan", "Noci pecan")),
    ("sunflower_seeds", (584, 21.0, 51.0, 20.0), "nuts", ["raw", "baked"],
     ("Sunflower Seeds", "Семечки подсолнуха", "Sonnenblumenkerne", "Semillas de girasol", "Graines de tournesol", "Semi di girasole")),
    ("pumpkin_seeds", (559, 30.0, 49.0, 11.0), "nuts", ["raw", "baked"],
     ("Pumpkin Seeds", "Тыквенные семечки", "Kürbiskerne", "Semillas de calabaza", "Graines de citrouille", "Semi di zucca")),
    ("chia_seeds", (486, 17.0, 31.0, 42.0), "nuts", ["raw"],
     ("Chia Seeds", "Семена чиа", "Chiasamen", "Semillas de chía", "Graines de chia", "Semi di chia")),
    ("flaxseeds", (534, 18.0, 42.0, 29.0), "nuts", ["raw"],
     ("Flaxseeds", "Семена льна", "Leinsamen", "Semillas de lino", "Graines de lin", "Semi di lino")),
    ("sesame_seeds", (573, 18.0, 50.0, 23.0), "nuts", ["raw"],
     ("Sesame Seeds", "Кунжут", "Sesamsamen", "Semillas de sésamo", "Graines de sésame", "Semi di sesamo")),

    # SWEETS & SNACKS
    ("chocolate_dark", (598, 7.8, 43.0, 46.0), "sweets", ["raw"],
     ("Dark Chocolate (70%)", "Тёмный шоколад (70%)", "Zartbitterschokolade", "Chocolate negro", "Chocolat noir", "Cioccolato fondente")),
    ("chocolate_milk", (535, 7.7, 30.0, 59.0), "sweets", ["raw"],
     ("Milk Chocolate", "Молочный шоколад", "Milchschokolade", "Chocolate con leche", "Chocolat au lait", "Cioccolato al latte")),
    ("honey", (304, 0.3, 0.0, 82.0), "sweets", ["raw"],
     ("Honey", "Мёд", "Honig", "Miel", "Miel", "Miele")),
    ("maple_syrup", (260, 0.0, 0.0, 67.0), "sweets", ["raw"],
     ("Maple Syrup", "Кленовый сироп", "Ahornsirup", "Jarabe de arce", "Sirop d'érable", "Sciroppo d'acero")),
    ("sugar_white", (387, 0.0, 0.0, 100.0), "sweets", ["raw"],
     ("White Sugar", "Белый сахар", "Weißzucker", "Azúcar blanco", "Sucre blanc", "Zucchero bianco")),
    ("potato_chips", (536, 7.0, 35.0, 53.0), "sweets", ["raw"],
     ("Potato Chips", "Картофельные чипсы", "Kartoffelchips", "Papas fritas", "Chips de pommes de terre", "Patatine fritte")),
    ("popcorn", (387, 13.0, 4.5, 78.0), "sweets", ["raw"],
     ("Popcorn (Air-popped)", "Попкорн", "Popcorn", "Palomitas", "Pop-corn", "Popcorn")),
"""

with open('generate_massive_foods.py', 'r') as f:
    content = f.read()

# Insert before "    # READY MEALS" or just after the last tuple in BASE_FOODS
parts = content.split("]\n\n# Create dictionaries")
if len(parts) == 2:
    new_content = parts[0] + ",\n" + extra_bases + "]\n\n# Create dictionaries" + parts[1]
    with open('generate_massive_foods.py', 'w') as f:
        f.write(new_content)
    print("Added 50+ new base foods. Will generate > 2500 total permutations per language!")
else:
    print("Failed to parse")
